require('dotenv').config();
const mongoose = require('mongoose');
const Service = require('../models/Service');
const connectDB = require('../config/db');

// Comprehensive seed data with 40 well-researched B2B companies
const mockServices = [
  // Technology - Cloud & Infrastructure
  {
    companyName: "Amazon Web Services",
    services: ["Cloud Infrastructure", "Cloud Computing", "Data Storage", "Machine Learning"],
    industry: "Technology",
    location: "Seattle, WA",
    companySize: "Large",
    description: "Leading cloud computing platform offering scalable infrastructure, storage, databases, and ML services to businesses worldwide.",
    rating: 4.7,
    verified: true,
    approved: true,
    website: "https://aws.amazon.com",
    quoteUrl: "https://aws.amazon.com/contact-us",
    email: "aws-sales@amazon.com",
    phone: "1-877-777-4827",
    founded: "2006",
    employees: "10000+",
    certifications: ["ISO 27001", "SOC 2", "PCI DSS"],
    linkedin: "https://linkedin.com/company/amazon-web-services"
  },
  {
    companyName: "Microsoft Azure",
    services: ["Cloud Infrastructure", "Cloud Computing", "Enterprise Software", "AI Services"],
    industry: "Technology",
    location: "Redmond, WA",
    companySize: "Large",
    description: "Comprehensive cloud platform with integrated tools and services for building, deploying, and managing enterprise applications.",
    rating: 4.6,
    verified: true,
    approved: true,
    website: "https://azure.microsoft.com",
    quoteUrl: "https://azure.microsoft.com/en-us/pricing/calculator",
    phone: "1-800-642-7676",
    founded: "2010",
    employees: "10000+",
    certifications: ["ISO 27001", "SOC 2", "HIPAA"],
    linkedin: "https://linkedin.com/showcase/microsoft-azure"
  },
  {
    companyName: "Google Cloud Platform",
    services: ["Cloud Infrastructure", "Data Analytics", "Machine Learning", "Cloud Computing"],
    industry: "Technology",
    location: "Mountain View, CA",
    companySize: "Large",
    description: "Enterprise-grade cloud computing services with advanced analytics, ML, and data processing capabilities.",
    rating: 4.5,
    verified: true,
    approved: true,
    website: "https://cloud.google.com",
    phone: "1-877-461-5637",
    founded: "2008",
    employees: "10000+",
    certifications: ["ISO 27001", "SOC 2", "HIPAA"],
    linkedin: "https://linkedin.com/showcase/google-cloud"
  },

  // Technology - Cybersecurity
  {
    companyName: "CrowdStrike",
    services: ["Cybersecurity", "Endpoint Protection", "Threat Intelligence", "Security Consulting"],
    industry: "Technology",
    location: "Austin, TX",
    companySize: "Large",
    description: "Cloud-native endpoint protection platform with AI-powered threat detection and response capabilities.",
    rating: 4.8,
    verified: true,
    approved: true,
    website: "https://www.crowdstrike.com",
    phone: "1-888-512-8906",
    founded: "2011",
    employees: "5000-10000",
    certifications: ["ISO 27001", "SOC 2"],
    linkedin: "https://linkedin.com/company/crowdstrike"
  },
  {
    companyName: "Palo Alto Networks",
    services: ["Cybersecurity", "Network Security", "Cloud Security", "Security Audits"],
    industry: "Technology",
    location: "Santa Clara, CA",
    companySize: "Large",
    description: "Next-generation cybersecurity platform providing network security, cloud security, and threat prevention.",
    rating: 4.7,
    verified: true,
    approved: true,
    website: "https://www.paloaltonetworks.com",
    phone: "1-866-320-4788",
    founded: "2005",
    employees: "10000+",
    certifications: ["ISO 27001", "SOC 2"],
    linkedin: "https://linkedin.com/company/palo-alto-networks"
  },

  // Technology - Communications
  {
    companyName: "Slack Technologies",
    services: ["Team Collaboration", "Business Communications", "Workflow Automation"],
    industry: "Technology",
    location: "San Francisco, CA",
    companySize: "Large",
    description: "Business communication platform that brings team collaboration and productivity tools into one unified workspace.",
    rating: 4.5,
    verified: true,
    approved: true,
    website: "https://slack.com",
    phone: "1-855-252-5354",
    founded: "2013",
    employees: "1000-5000",
    certifications: ["SOC 2", "ISO 27001"],
    linkedin: "https://linkedin.com/company/slack-technologies"
  },
  {
    companyName: "Zoom Video Communications",
    services: ["Video Conferencing", "Communications", "UCaaS", "Webinar Platform"],
    industry: "Technology",
    location: "San Jose, CA",
    companySize: "Large",
    description: "Leading video-first unified communications platform for meetings, chat, phone, and webinars.",
    rating: 4.5,
    verified: true,
    approved: true,
    website: "https://www.zoom.com",
    phone: "1-888-799-9666",
    founded: "2011",
    employees: "5000-10000",
    certifications: ["SOC 2", "ISO 27001", "HIPAA"],
    linkedin: "https://linkedin.com/company/zoom"
  },

  // Technology - Software & Development
  {
    companyName: "Atlassian",
    services: ["Project Management", "Software Development Tools", "Team Collaboration"],
    industry: "Technology",
    location: "San Francisco, CA",
    companySize: "Large",
    description: "Provider of collaboration and productivity software including Jira, Confluence, and Trello for software teams.",
    rating: 4.4,
    verified: true,
    approved: true,
    website: "https://www.atlassian.com",
    phone: "1-800-666-4524",
    founded: "2002",
    employees: "5000-10000",
    certifications: ["SOC 2", "ISO 27001"],
    linkedin: "https://linkedin.com/company/atlassian"
  },
  {
    companyName: "GitHub",
    services: ["Software Development Tools", "Code Repository", "DevOps", "CI/CD"],
    industry: "Technology",
    location: "San Francisco, CA",
    companySize: "Large",
    description: "World's leading software development platform for version control, collaboration, and DevOps workflows.",
    rating: 4.6,
    verified: true,
    approved: true,
    website: "https://github.com",
    founded: "2008",
    employees: "1000-5000",
    certifications: ["SOC 2", "ISO 27001"],
    linkedin: "https://linkedin.com/company/github"
  },

  // Marketing
  {
    companyName: "HubSpot",
    services: ["Marketing Automation", "CRM", "B2B Marketing", "Content Strategy"],
    industry: "Marketing",
    location: "Cambridge, MA",
    companySize: "Large",
    description: "All-in-one inbound marketing, sales, and customer service platform with powerful CRM capabilities.",
    rating: 4.5,
    verified: true,
    approved: true,
    website: "https://www.hubspot.com",
    phone: "1-888-482-7768",
    founded: "2006",
    employees: "5000-10000",
    certifications: ["ISO 27001", "SOC 2"],
    linkedin: "https://linkedin.com/company/hubspot"
  },
  {
    companyName: "Salesforce Marketing Cloud",
    services: ["Marketing Automation", "Digital Marketing", "Customer Engagement", "Email Marketing"],
    industry: "Marketing",
    location: "San Francisco, CA",
    companySize: "Large",
    description: "Enterprise marketing automation and customer engagement platform with AI-powered insights.",
    rating: 4.3,
    verified: true,
    approved: true,
    website: "https://www.salesforce.com/products/marketing-cloud",
    phone: "1-800-667-6389",
    founded: "1999",
    employees: "10000+",
    certifications: ["ISO 27001", "SOC 2"],
    linkedin: "https://linkedin.com/company/salesforce"
  },
  {
    companyName: "Mailchimp",
    services: ["Email Marketing", "Marketing Automation", "Digital Marketing", "Analytics"],
    industry: "Marketing",
    location: "Atlanta, GA",
    companySize: "Medium",
    description: "Popular email marketing and automation platform designed for small to medium-sized businesses.",
    rating: 4.4,
    verified: true,
    approved: true,
    website: "https://mailchimp.com",
    founded: "2001",
    employees: "1000-5000",
    certifications: ["SOC 2"],
    linkedin: "https://linkedin.com/company/mailchimp"
  },

  // Finance & Accounting
  {
    companyName: "Stripe",
    services: ["Payment Processing", "Financial Services", "Fintech Solutions"],
    industry: "Finance",
    location: "San Francisco, CA",
    companySize: "Large",
    description: "Payment infrastructure for the internet, enabling businesses to accept and manage online payments.",
    rating: 4.6,
    verified: true,
    approved: true,
    website: "https://stripe.com",
    founded: "2010",
    employees: "5000-10000",
    certifications: ["PCI DSS", "SOC 2", "ISO 27001"],
    linkedin: "https://linkedin.com/company/stripe"
  },
  {
    companyName: "Intuit QuickBooks",
    services: ["Accounting Software", "Financial Consulting", "Tax Services", "Payroll"],
    industry: "Finance",
    location: "Mountain View, CA",
    companySize: "Large",
    description: "Leading accounting software and financial management solutions for small and medium-sized businesses.",
    rating: 4.3,
    verified: true,
    approved: true,
    website: "https://quickbooks.intuit.com",
    phone: "1-800-446-8848",
    founded: "1983",
    employees: "10000+",
    certifications: ["SOC 2"],
    linkedin: "https://linkedin.com/company/intuit"
  },
  {
    companyName: "Xero",
    services: ["Accounting Software", "Financial Consulting", "Payroll", "Expense Management"],
    industry: "Finance",
    location: "Wellington, New Zealand",
    companySize: "Medium",
    description: "Cloud-based accounting software platform for small businesses with real-time financial insights.",
    rating: 4.5,
    verified: true,
    approved: true,
    website: "https://www.xero.com",
    founded: "2006",
    employees: "1000-5000",
    certifications: ["ISO 27001", "SOC 2"],
    linkedin: "https://linkedin.com/company/xero"
  },

  // Human Resources
  {
    companyName: "Workday",
    services: ["HR Management", "Talent Acquisition", "Payroll", "Workforce Analytics"],
    industry: "Human Resources",
    location: "Pleasanton, CA",
    companySize: "Large",
    description: "Enterprise cloud platform for finance and HR with unified analytics and planning capabilities.",
    rating: 4.4,
    verified: true,
    approved: true,
    website: "https://www.workday.com",
    phone: "1-877-967-5329",
    founded: "2005",
    employees: "10000+",
    certifications: ["ISO 27001", "SOC 2"],
    linkedin: "https://linkedin.com/company/workday"
  },
  {
    companyName: "BambooHR",
    services: ["HR Software", "Talent Management", "Employee Onboarding", "Performance Management"],
    industry: "Human Resources",
    location: "Lindon, UT",
    companySize: "Medium",
    description: "All-in-one HR software for small and medium businesses with intuitive employee management tools.",
    rating: 4.6,
    verified: true,
    approved: true,
    website: "https://www.bamboohr.com",
    phone: "1-866-387-9595",
    founded: "2008",
    employees: "500-1000",
    certifications: ["SOC 2"],
    linkedin: "https://linkedin.com/company/bamboohr"
  },
  {
    companyName: "ADP",
    services: ["Payroll Services", "HR Consulting", "Benefits Administration", "Compliance"],
    industry: "Human Resources",
    location: "Roseland, NJ",
    companySize: "Large",
    description: "Comprehensive human capital management solutions including payroll, HR, and benefits administration.",
    rating: 4.2,
    verified: true,
    approved: true,
    website: "https://www.adp.com",
    phone: "1-800-225-5237",
    founded: "1949",
    employees: "10000+",
    certifications: ["SOC 2", "ISO 27001"],
    linkedin: "https://linkedin.com/company/adp"
  },

  // Legal
  {
    companyName: "LegalZoom",
    services: ["Legal Services", "Business Formation", "Trademark Registration", "Legal Consulting"],
    industry: "Legal",
    location: "Glendale, CA",
    companySize: "Medium",
    description: "Online platform providing legal solutions for business formation, intellectual property, and estate planning.",
    rating: 4.3,
    verified: true,
    approved: true,
    website: "https://www.legalzoom.com",
    phone: "1-800-773-0888",
    founded: "2001",
    employees: "1000-5000",
    linkedin: "https://linkedin.com/company/legalzoom"
  },
  {
    companyName: "Rocket Lawyer",
    services: ["Legal Services", "Document Automation", "Legal Consulting", "Compliance"],
    industry: "Legal",
    location: "San Francisco, CA",
    companySize: "Small",
    description: "Online legal services platform providing affordable legal documents and attorney consultations.",
    rating: 4.2,
    verified: true,
    approved: true,
    website: "https://www.rocketlawyer.com",
    phone: "1-877-881-0947",
    founded: "2008",
    employees: "100-500",
    linkedin: "https://linkedin.com/company/rocket-lawyer"
  },

  // Healthcare
  {
    companyName: "Epic Systems",
    services: ["Healthcare IT", "Electronic Health Records", "Healthcare Consulting"],
    industry: "Healthcare",
    location: "Verona, WI",
    companySize: "Large",
    description: "Leading electronic health records software provider for hospitals and healthcare organizations.",
    rating: 4.5,
    verified: true,
    approved: true,
    website: "https://www.epic.com",
    phone: "1-608-271-9000",
    founded: "1979",
    employees: "10000+",
    certifications: ["HIPAA", "SOC 2"],
    linkedin: "https://linkedin.com/company/epic-systems"
  },
  {
    companyName: "Teladoc Health",
    services: ["Telehealth Services", "Healthcare Technology", "Virtual Care"],
    industry: "Healthcare",
    location: "Purchase, NY",
    companySize: "Large",
    description: "Virtual healthcare platform connecting patients with healthcare professionals remotely.",
    rating: 4.3,
    verified: true,
    approved: true,
    website: "https://www.teladoc.com",
    phone: "1-800-835-2362",
    founded: "2002",
    employees: "5000-10000",
    certifications: ["HIPAA", "SOC 2"],
    linkedin: "https://linkedin.com/company/teladoc-health"
  },

  // Manufacturing & Supply Chain
  {
    companyName: "SAP",
    services: ["ERP Software", "Supply Chain Management", "Business Intelligence"],
    industry: "Manufacturing",
    location: "Walldorf, Germany",
    companySize: "Large",
    description: "Enterprise resource planning software and business process management solutions for manufacturers.",
    rating: 4.3,
    verified: true,
    approved: true,
    website: "https://www.sap.com",
    phone: "1-800-872-1727",
    founded: "1972",
    employees: "10000+",
    certifications: ["ISO 27001", "SOC 2"],
    linkedin: "https://linkedin.com/company/sap"
  },
  {
    companyName: "Oracle NetSuite",
    services: ["ERP Software", "Supply Chain Optimization", "Financial Management"],
    industry: "Manufacturing",
    location: "Austin, TX",
    companySize: "Large",
    description: "Cloud ERP solution for manufacturing, inventory management, and supply chain operations.",
    rating: 4.2,
    verified: true,
    approved: true,
    website: "https://www.netsuite.com",
    phone: "1-877-638-7848",
    founded: "1998",
    employees: "5000-10000",
    certifications: ["SOC 2", "ISO 27001"],
    linkedin: "https://linkedin.com/company/netsuite"
  },
  {
    companyName: "Shopify Plus",
    services: ["E-commerce Platform", "Supply Chain Management", "Order Fulfillment"],
    industry: "Manufacturing",
    location: "Ottawa, Canada",
    companySize: "Large",
    description: "Enterprise e-commerce platform with integrated supply chain and fulfillment capabilities.",
    rating: 4.6,
    verified: true,
    approved: true,
    website: "https://www.shopify.com/plus",
    phone: "1-888-746-7439",
    founded: "2006",
    employees: "5000-10000",
    certifications: ["PCI DSS", "SOC 2"],
    linkedin: "https://linkedin.com/company/shopify"
  },

  // Creative & Design
  {
    companyName: "Adobe Creative Cloud",
    services: ["Creative Software", "Design Tools", "Video Production", "UX/UI Design"],
    industry: "Creative",
    location: "San Jose, CA",
    companySize: "Large",
    description: "Industry-standard creative tools including Photoshop, Illustrator, and Premiere for design professionals.",
    rating: 4.5,
    verified: true,
    approved: true,
    website: "https://www.adobe.com",
    phone: "1-800-833-6687",
    founded: "1982",
    employees: "10000+",
    certifications: ["SOC 2", "ISO 27001"],
    linkedin: "https://linkedin.com/company/adobe"
  },
  {
    companyName: "Canva for Teams",
    services: ["Graphic Design", "Brand Identity", "Marketing Materials", "Design Collaboration"],
    industry: "Creative",
    location: "Sydney, Australia",
    companySize: "Medium",
    description: "Collaborative design platform enabling teams to create professional graphics and marketing materials.",
    rating: 4.7,
    verified: true,
    approved: true,
    website: "https://www.canva.com/teams",
    founded: "2012",
    employees: "1000-5000",
    certifications: ["SOC 2"],
    linkedin: "https://linkedin.com/company/canva"
  },
  {
    companyName: "Figma",
    services: ["UX/UI Design", "Design Collaboration", "Prototyping", "Design Systems"],
    industry: "Creative",
    location: "San Francisco, CA",
    companySize: "Medium",
    description: "Collaborative interface design tool for creating, prototyping, and managing design systems.",
    rating: 4.8,
    verified: true,
    approved: true,
    website: "https://www.figma.com",
    founded: "2012",
    employees: "500-1000",
    certifications: ["SOC 2"],
    linkedin: "https://linkedin.com/company/figma"
  },

  // Real Estate
  {
    companyName: "WeWork",
    services: ["Coworking Spaces", "Office Space Management", "Real Estate Solutions"],
    industry: "Real Estate",
    location: "New York, NY",
    companySize: "Large",
    description: "Flexible workspace solutions and commercial real estate services for businesses of all sizes.",
    rating: 4.0,
    verified: true,
    approved: true,
    website: "https://www.wework.com",
    phone: "1-888-977-4184",
    founded: "2010",
    employees: "5000-10000",
    linkedin: "https://linkedin.com/company/wework"
  },
  {
    companyName: "CBRE Group",
    services: ["Commercial Real Estate", "Property Management", "Real Estate Consulting"],
    industry: "Real Estate",
    location: "Dallas, TX",
    companySize: "Large",
    description: "World's largest commercial real estate services and investment firm.",
    rating: 4.3,
    verified: true,
    approved: true,
    website: "https://www.cbre.com",
    phone: "1-214-979-6100",
    founded: "1906",
    employees: "10000+",
    linkedin: "https://linkedin.com/company/cbre"
  },

  // Data & Analytics
  {
    companyName: "Tableau",
    services: ["Data Visualization", "Business Intelligence", "Data Analytics"],
    industry: "Technology",
    location: "Seattle, WA",
    companySize: "Large",
    description: "Visual analytics platform transforming data into actionable insights with interactive dashboards.",
    rating: 4.5,
    verified: true,
    approved: true,
    website: "https://www.tableau.com",
    phone: "1-877-822-5328",
    founded: "2003",
    employees: "5000-10000",
    certifications: ["SOC 2", "ISO 27001"],
    linkedin: "https://linkedin.com/company/tableau-software"
  },
  {
    companyName: "Snowflake",
    services: ["Cloud Data Warehouse", "Data Analytics", "Data Sharing"],
    industry: "Technology",
    location: "Bozeman, MT",
    companySize: "Large",
    description: "Cloud data platform enabling data storage, processing, and analytic solutions.",
    rating: 4.6,
    verified: true,
    approved: true,
    website: "https://www.snowflake.com",
    phone: "1-844-766-9355",
    founded: "2012",
    employees: "5000-10000",
    certifications: ["SOC 2", "ISO 27001", "HIPAA"],
    linkedin: "https://linkedin.com/company/snowflake-computing"
  },
  {
    companyName: "Databricks",
    services: ["Data Analytics", "Machine Learning", "Big Data Processing"],
    industry: "Technology",
    location: "San Francisco, CA",
    companySize: "Large",
    description: "Unified analytics platform combining data engineering, data science, and machine learning.",
    rating: 4.7,
    verified: true,
    approved: true,
    website: "https://www.databricks.com",
    founded: "2013",
    employees: "1000-5000",
    certifications: ["SOC 2", "ISO 27001"],
    linkedin: "https://linkedin.com/company/databricks"
  },

  // Customer Support & CRM
  {
    companyName: "Zendesk",
    services: ["Customer Support Software", "Help Desk", "Customer Engagement"],
    industry: "Technology",
    location: "San Francisco, CA",
    companySize: "Large",
    description: "Customer service and engagement platform with ticketing, self-service, and messaging tools.",
    rating: 4.3,
    verified: true,
    approved: true,
    website: "https://www.zendesk.com",
    phone: "1-888-670-4887",
    founded: "2007",
    employees: "5000-10000",
    certifications: ["SOC 2", "ISO 27001"],
    linkedin: "https://linkedin.com/company/zendesk"
  },
  {
    companyName: "Salesforce",
    services: ["CRM", "Sales Automation", "Customer Service", "Marketing Automation"],
    industry: "Technology",
    location: "San Francisco, CA",
    companySize: "Large",
    description: "World's #1 CRM platform with comprehensive sales, service, and marketing solutions.",
    rating: 4.4,
    verified: true,
    approved: true,
    website: "https://www.salesforce.com",
    phone: "1-800-667-6389",
    founded: "1999",
    employees: "10000+",
    certifications: ["ISO 27001", "SOC 2"],
    linkedin: "https://linkedin.com/company/salesforce"
  },

  // Project Management
  {
    companyName: "Asana",
    services: ["Project Management", "Team Collaboration", "Workflow Automation"],
    industry: "Technology",
    location: "San Francisco, CA",
    companySize: "Medium",
    description: "Work management platform helping teams orchestrate work, from daily tasks to strategic initiatives.",
    rating: 4.4,
    verified: true,
    approved: true,
    website: "https://asana.com",
    founded: "2008",
    employees: "1000-5000",
    certifications: ["SOC 2", "ISO 27001"],
    linkedin: "https://linkedin.com/company/asana"
  },
  {
    companyName: "Monday.com",
    services: ["Project Management", "Workflow Automation", "Team Collaboration"],
    industry: "Technology",
    location: "Tel Aviv, Israel",
    companySize: "Medium",
    description: "Work operating system enabling teams to run projects and workflows with confidence.",
    rating: 4.6,
    verified: true,
    approved: true,
    website: "https://monday.com",
    founded: "2012",
    employees: "1000-5000",
    certifications: ["SOC 2", "ISO 27001"],
    linkedin: "https://linkedin.com/company/mondaydotcom"
  },

  // Document Management
  {
    companyName: "DocuSign",
    services: ["Digital Signature", "Document Management", "Contract Management"],
    industry: "Technology",
    location: "San Francisco, CA",
    companySize: "Large",
    description: "Electronic signature and digital transaction management platform for secure document workflows.",
    rating: 4.5,
    verified: true,
    approved: true,
    website: "https://www.docusign.com",
    phone: "1-877-720-2040",
    founded: "2003",
    employees: "5000-10000",
    certifications: ["SOC 2", "ISO 27001"],
    linkedin: "https://linkedin.com/company/docusign"
  },
  {
    companyName: "Dropbox Business",
    services: ["Cloud Storage", "File Sharing", "Document Management", "Team Collaboration"],
    industry: "Technology",
    location: "San Francisco, CA",
    companySize: "Large",
    description: "Secure file storage and collaboration platform for modern distributed teams.",
    rating: 4.4,
    verified: true,
    approved: true,
    website: "https://www.dropbox.com/business",
    phone: "1-844-327-6794",
    founded: "2007",
    employees: "1000-5000",
    certifications: ["SOC 2", "ISO 27001"],
    linkedin: "https://linkedin.com/company/dropbox"
  }
];

const seedDatabase = async () => {
  try {
    // Connect to MongoDB
    await connectDB();

    // Clear existing data
    await Service.deleteMany({});
    console.log('Cleared existing services');

    // Insert mock data
    await Service.insertMany(mockServices);
    console.log('Mock data inserted successfully');

    console.log(`Seeded ${mockServices.length} services`);
    process.exit(0);
  } catch (error) {
    console.error('Error seeding database:', error);
    process.exit(1);
  }
};

seedDatabase();
